eggjs/tegg

- plugin/controller/package.json
Related ISSUE:
https://github.com/eggjs/tegg/issues/15
Related PR:
https://github.com/eggjs/tegg/pull/17
I think `path-to-regexp@1.8.0` should be added in dependencies to avoid MISSING ERROR when add `@eggjs/tegg-controller-plugin` additionally
`path-to-regexp@2.x` no longer has default export.
> fix: path-to-regexp deps for tegg-controller-plugin

- core/metadata/src/errors.ts
- core/metadata/src/impl/EggPrototypeBuilder.ts
- core/metadata/test/LoadUnit.test.ts
- core/metadata/test/fixtures/modules/incompatible-proto-inject/package.json
- core/metadata/test/fixtures/modules/incompatible-proto-inject/test.ts
如果发现在 SingletonProto 中 inject ContextProto 报通用错误码错误，不然执行到后面都是 `ctx is required` 的错误，让人比较困惑。
> fix: should throw when inject context proto in singleton

- core/common-util/src/ModuleConfig.ts
- core/common-util/test/fixtures/apps/app-with-no-module-json/.sff/.other/module-d/package.json
- core/common-util/test/fixtures/apps/app-with-no-module-json/app/module-b/test/fixtures/module-e/package.json
- core/loader/src/LoaderUtil.ts
- core/loader/test/Loader.test.ts
- core/loader/test/fixtures/modules/module-with-extra/.dist/ThrowError.ts
- core/loader/test/fixtures/modules/module-with-test/.gitignore
- core/loader/test/fixtures/modules/module-with-test/coverage/fixtures/UserRepo.ts
优化扫文件的逻辑。
1. 把 coverage 目录也加上忽略的目录
2. 将 `!.*/**` 改成 `!+(.*)/**` 以匹配 .xx/.xx/ 这种目录结构
第二点再详细描述一下，因为 dot 没开，所以后面的 `**` 不会匹配 .xxx 这种路径，所以 `.*/**` 只能匹配 `.xxx/xxx/xx` 这种目录，而不能匹配 `.xxx/.xxx/xxxx` 这种。从而导致 globby 在进行是否要进行深度遍历的时候没法 match 到，从而一直遍历进去。
这个带来的问题就是，当一旦存在 `.xxx/.xxx/node_modules` 之后，globby.sync 就能扫到 oom 。
而配成 `!+(.*)/**` 就能解决这个问题，因为生成的正则不太一样，能匹配 `.xxx` 直接在第一层级就停止进一步的深度遍历，估计跟 micromatch 的实现有关
复现 case：https://github.com/whxaxes/test-globby
> feat: optimize globby filepattern

- core/dynamic-inject-runtime/test/index.test.ts
- core/metadata/src/impl/ModuleLoadUnit.ts
- plugin/tegg/lib/EggAppLoader.ts
- plugin/tegg/test/DynamicInject.test.ts
- plugin/tegg/test/fixtures/apps/dynamic-inject-app/app/controller/app.ts
- plugin/tegg/test/fixtures/apps/dynamic-inject-app/app/router.ts
- plugin/tegg/test/fixtures/apps/dynamic-inject-app/modules/dynamic-inject-module/SingletonHelloService.ts
app.eggObjectFactory conflict with dynamic-inject plugin
> fix: add app.eggObjectFactory to blacklist

- core/runtime/src/model/AbstractEggContext.ts
- core/runtime/test/EggObject.test.ts
应该将 eggObjectPromiseMap 里的 Map 也清理掉，减少内存占用
> fix: should clear object promise map

- core/orm-decorator/README.md
- core/orm-decorator/src/decorator/Model.ts
- core/orm-decorator/src/util/ModelMetadataUtil.ts
- plugin/orm/app.ts
- plugin/orm/lib/ContextModeObject.ts
- plugin/orm/lib/ContextModelProto.ts
- plugin/orm/lib/LeoricRegister.ts
- plugin/orm/lib/ModelProtoHook.ts
- plugin/orm/package.json
- plugin/orm/test/fixtures/apps/orm-app/app.ts
- plugin/orm/test/fixtures/apps/orm-app/modules/orm-module/AppService.ts
- plugin/orm/test/fixtures/apps/orm-app/modules/orm-module/PkgService.ts
- plugin/orm/test/index.test.ts
- plugin/orm/typings/index.d.ts
> feat: impl Inject Model

- plugin/tegg/lib/EggAppLoader.ts
- plugin/tegg/test/BackgroundTask.test.ts
- plugin/tegg/test/fixtures/apps/background-app/app/controller/app.ts
- plugin/tegg/test/fixtures/apps/background-app/app/extend/context.ts
- plugin/tegg/test/fixtures/apps/background-app/app/router.ts
- plugin/tegg/test/fixtures/apps/background-app/modules/multi-module-background/BackgroundService.ts
当 background task 超时后，如果读 egg 中的兼容对象，ctx 是 undefined ，错误比较误导人，所以加一下通用错误码。
> fix: optimize backgroud output

- plugin/orm/test/fixtures/apps/orm-app/config/config.default.js
dns lookup with node18 perfer ipv6,localhost
will be resolved to ::1, and mysql listen
bind to 127.0.0.1. It will cause conn refused.
So use 127.0.0.1 instead of localhost.
> ci: fix orm ut in node18 with macos

- core/controller-decorator/index.ts
- core/controller-decorator/src/decorator/http/Host.ts
- core/controller-decorator/src/impl/http/HTTPControllerMetaBuilder.ts
- core/controller-decorator/src/impl/http/HTTPControllerMethodMetaBuilder.ts
- core/controller-decorator/src/model/HTTPControllerMeta.ts
- core/controller-decorator/src/model/HTTPMethodMeta.ts
- core/controller-decorator/src/util/ControllerInfoUtil.ts
- core/controller-decorator/src/util/MethodInfoUtil.ts
- core/controller-decorator/test/fixtures/HostController.ts
- core/controller-decorator/test/http/Host.test.ts
- plugin/controller/README.md
- plugin/controller/lib/RootProtoManager.ts
- plugin/controller/lib/impl/http/HTTPControllerRegister.ts
- plugin/controller/lib/impl/http/HTTPMethodRegister.ts
- plugin/controller/test/fixtures/apps/host-controller-app/app/controller/AppController.ts
- plugin/controller/test/fixtures/apps/host-controller-app/app/controller/AppController2.ts
- plugin/controller/test/fixtures/apps/host-controller-app/config/config.default.js
- plugin/controller/test/fixtures/apps/host-controller-app/config/plugin.js
- plugin/controller/test/fixtures/apps/host-controller-app/package.json
- plugin/controller/test/fixtures/apps/http-conflict-app/app/controller/HostController1.ts
- plugin/controller/test/fixtures/apps/http-conflict-app/app/controller/HostController2.ts
- plugin/controller/test/http/host.test.ts
- plugin/controller/test/lib/HTTPMethodRegister.test.ts
> feat: impl Host decorator

- core/eventbus-decorator/README.md
- core/eventbus-decorator/src/EventBus.ts
- core/eventbus-runtime/package.json
- core/eventbus-runtime/src/SingletonEventBus.ts
- core/eventbus-runtime/test/EventBus.test.ts
- plugin/eventbus/lib/EggContextEventBus.ts
- plugin/eventbus/package.json
- plugin/eventbus/test/eventbus.test.ts
- plugin/eventbus/test/fixtures/apps/event-app/app/event-module/HelloService.ts
- plugin/schedule/lib/ScheduleSubscriberRegister.ts
> feat: implement cork/uncork for eventbus

- core/aop-decorator/src/decorator/Advice.ts
- core/aop-decorator/test/AspectMetaBuilder.test.ts
> fix: fix file path for advice decorator

- core/common-util/src/ModuleConfig.ts
- core/common-util/test/ModuleConfig.test.ts
- core/common-util/test/fixtures/monorepo/node_modules/a
- core/common-util/test/fixtures/monorepo/packages/a/node_modules/c/package.json
- core/common-util/test/fixtures/monorepo/packages/a/package.json
- core/common-util/test/fixtures/monorepo/packages/b/package.json
- core/common-util/test/fixtures/monorepo/packages/d/node_modules/e/package.json
- core/common-util/test/fixtures/monorepo/packages/d/node_modules/f/package.json
- core/common-util/test/fixtures/monorepo/packages/d/package.json
> fix: use require.resolve instead path.join to resolve dependencies path

- README.md
- plugin/aop/package.json
- plugin/controller/package.json
- plugin/eventbus/package.json
- plugin/orm/package.json
- plugin/schedule/package.json
- plugin/tegg/app/extend/application.unittest.ts
- plugin/tegg/lib/EggContextHandler.ts
- plugin/tegg/package.json
- plugin/tegg/test/AccessLevelCheck.test.ts
- plugin/tegg/test/EggCompatible.test.ts
- plugin/tegg/test/SameProtoName.test.ts
- plugin/tegg/test/app/extend/application.unittest.test.ts
- plugin/tegg/test/app/extend/context.test.ts
- plugin/tegg/typings/index.d.ts
> feat: impl mockModuleContextScope

- plugin/eventbus/lib/EggContextEventBus.ts
- plugin/eventbus/test/eventbus.test.ts
> fix: cork/uncork should can be called multi times in same ctx

- core/runtime/src/impl/EggObjectUtil.ts
- core/runtime/test/EggObject.test.ts
Mock property will configure property.
> fix: inject property should be configurable

- core/background-task/src/BackgroundTaskHelper.ts
- core/background-task/test/BackgroundTaskHelper.test.ts
- plugin/tegg/test/app/extend/context.test.ts
> fix: BackgroundTaskHelper should support recursively call

- plugin/tegg/lib/EggContextCompatibleHook.ts
All ctx proto has been init, so trigger singleton
proto init is useless.
> fix: remove useless init singleton proto

- core/transaction-decorator/CHANGELOG.md
- core/transaction-decorator/README.md
- core/transaction-decorator/index.ts
- core/transaction-decorator/package.json
- core/transaction-decorator/src/Common.ts
- core/transaction-decorator/src/builder/TransactionMetaBuilder.ts
- core/transaction-decorator/src/decorator/Transactional.ts
- core/transaction-decorator/src/model/TransactionMetadata.ts
- core/transaction-decorator/src/util/TransactionMetadataUtil.ts
- core/transaction-decorator/test/builder/TransactionMetaBuilder.test.ts
- core/transaction-decorator/test/fixtures/transaction.ts
- core/transaction-decorator/tsconfig.json
- core/transaction-decorator/tsconfig.pub.json
消费侧将使用 https://github.com/cyjake/leori
cc @killagu
> feat: 支持事务 decorator

- core/transaction-decorator/README.md
- core/transaction-decorator/src/Common.ts
- core/transaction-decorator/src/decorator/Transactional.ts
- core/transaction-decorator/src/model/TransactionMetadata.ts
- core/transaction-decorator/test/builder/TransactionMetaBuilder.test.ts
- core/transaction-decorator/test/fixtures/transaction.ts
> feat: 事务注解增加数据源选项

- plugin/controller/test/fixtures/apps/controller-app/app/controller/MiddlewareController.ts
- plugin/controller/test/fixtures/apps/controller-app/app/middleware/call_module.ts
- plugin/controller/test/http/middleware.test.ts
- plugin/tegg/lib/EggContextCompatibleHook.ts
> fix: ensure ContextInitiator be called after ctx ready

- core/aop-runtime/src/LoadUnitAopHook.ts
- plugin/aop/app.ts
- plugin/aop/lib/AopContextHook.ts
- plugin/aop/test/aop.test.ts
- plugin/aop/test/fixtures/apps/aop-app/app/controller/app.ts
- plugin/aop/test/fixtures/apps/aop-app/app/router.ts
- plugin/aop/test/fixtures/apps/aop-app/modules/aop-module/Hello.ts
> fix: init all context advice if root proto miss

- plugin/aop/lib/AopContextHook.ts
- plugin/aop/package.json
```
node_modules/@eggjs/tegg-aop-plugin/app.js, error: Cannot find module '@eggjs/aop-decorator'
Require stack:
- ~/node_modules/@eggjs/tegg-aop-plugin/lib/AopContextHook.js
```
> fix: add missing deps on @eggjs/tegg-aop-plugin

- standalone/standalone/index.ts
> feat: export EggModuleLoader in standalone

- standalone/standalone/package.json
- standalone/standalone/src/ConfigSourceLoadUnitHook.ts
- standalone/standalone/src/LoadUnitInnerClassHook.ts
- standalone/standalone/src/Runner.ts
- standalone/standalone/test/fixtures/aop-module/Hello.ts
- standalone/standalone/test/fixtures/aop-module/main.ts
- standalone/standalone/test/fixtures/aop-module/package.json
- standalone/standalone/test/fixtures/dynamic-inject-module/AbstractContextHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/AbstractSingletonHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/FooType.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/HelloService.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/decorator/ContextHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/decorator/SingletonHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/impl/BarContextHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/impl/BarSingletonHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/impl/FooContextHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/impl/FooSingletonHello.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/main.ts
- standalone/standalone/test/fixtures/dynamic-inject-module/package.json
- standalone/standalone/test/index.test.ts
> feat: add aop runtime/dynamic inject runtime for standalone

- standalone/standalone/src/Runner.ts
> feat: add load units function

- .gitignore
- standalone/standalone/src/Runner.ts
- standalone/standalone/test/fixtures/dependency/foo.ts
- standalone/standalone/test/fixtures/dependency/node_modules/dependency-1/package.json
- standalone/standalone/test/fixtures/dependency/node_modules/dependency-2/foo.js
- standalone/standalone/test/fixtures/dependency/node_modules/dependency-2/module.yml
- standalone/standalone/test/fixtures/dependency/node_modules/dependency-2/package.json
- standalone/standalone/test/fixtures/dependency/package.json
- standalone/standalone/test/index.test.ts
> feat: support dependency module for standalone

- core/core-decorator/src/decorator/MultiInstanceProto.ts
- core/core-decorator/src/decorator/Prototype.ts
- core/core-decorator/src/model/EggMultiInstancePrototypeInfo.ts
- core/core-decorator/src/model/EggPrototypeInfo.ts
- core/core-decorator/test/decorators.test.ts
- core/metadata/src/factory/EggPrototypeCreatorFactory.ts
- core/metadata/src/impl/EggPrototypeBuilder.ts
- core/metadata/src/impl/EggPrototypeImpl.ts
- core/metadata/src/model/EggPrototype.ts
- core/metadata/test/LoadUnit.test.ts
- standalone/standalone/src/StandaloneInnerObjectProto.ts
- standalone/standalone/test/index.test.ts
> feat: add className property to EggPrototypeInfo

- core/runtime/src/factory/EggContainerFactory.ts
- core/runtime/test/LoadUnitInstance.test.ts
- plugin/tegg/app/extend/application.ts
- plugin/tegg/app/extend/context.ts
> feat: getObject support MultiInstanceProto

- plugin/tegg/lib/ModuleConfigLoader.ts
- plugin/tegg/package.json
- plugin/tegg/test/ModuleConfig.test.ts
- plugin/tegg/test/fixtures/apps/inject-module-config/app.ts
- plugin/tegg/test/fixtures/apps/inject-module-config/app/controller/app.ts
- plugin/tegg/test/fixtures/apps/inject-module-config/app/router.ts
- plugin/tegg/test/fixtures/apps/inject-module-config/app/typings/index.d.ts
- plugin/tegg/test/fixtures/apps/inject-module-config/modules/module-with-overwrite-config/bar.ts
- plugin/tegg/test/fixtures/apps/inject-module-config/modules/module-with-overwrite-config/module.unittest.yml
- plugin/tegg/test/fixtures/apps/inject-module-config/modules/module-with-overwrite-config/module.yml
- plugin/tegg/test/fixtures/apps/inject-module-config/modules/module-with-overwrite-config/package.json
- `@eggjs/tegg-plugin`
- `@eggjs/tegg-config`
module.yml/json 存放一些敏感配置 例如 db password（kms:encodepassword....），我们需要在应用启动前将其配置解密还原成明文数据字段
目前看到的注入点 app.moduleConfigs，所以需要 inject moduleConfig 优先读取 app.moduleConfigs 数据对象，确保服务在注入的时候拿到的是解密后配置
> feat: inject moduleConfig read from tegg-config app.moduleConfigs config

- plugin/orm/lib/LeoricRegister.ts
- plugin/orm/package.json
- plugin/orm
- changed the imported `hookNames` from internal module path to package named exports
> chore: import hookNames from package exports

- core/eventbus-decorator/README.md
- core/eventbus-decorator/index.ts
- core/eventbus-decorator/src/Event.ts
- core/eventbus-decorator/src/EventBus.ts
- core/eventbus-decorator/src/EventContext.ts
- core/eventbus-decorator/src/EventInfoUtil.ts
- core/eventbus-decorator/test/Event.test.ts
- core/eventbus-decorator/test/fixtures/empty-handle.ts
- core/eventbus-decorator/test/fixtures/event-handle-with-context.ts
- core/eventbus-decorator/test/fixtures/multiple-events-handle.ts
- core/eventbus-decorator/test/fixtures/right-event-handle.ts
- core/eventbus-runtime/src/EventHandlerFactory.ts
- core/eventbus-runtime/src/SingletonEventBus.ts
- core/eventbus-runtime/test/EventBus.test.ts
- core/eventbus-runtime/test/fixtures/modules/event/MultiEventWithContext.ts
- plugin/eventbus/lib/EggContextEventBus.ts
- plugin/eventbus/lib/EventHandlerProtoManager.ts
- plugin/eventbus/test/eventbus.test.ts
- plugin/eventbus/test/fixtures/apps/event-app/app/event-module/HelloService.ts
- plugin/eventbus/test/fixtures/apps/event-app/app/event-module/MultiEventHandler.ts
`plugin/eventbus`  `eventbus-decorator`  `eventbus-runtime` 
allow a handler to subscribe to multiple events
> feat(eventbus): allow a handler to subscribe to multiple events

- core/common-util/src/ModuleConfig.ts
- standalone/standalone/test/fixtures/module-with-empty-config/foo.ts
- standalone/standalone/test/fixtures/module-with-empty-config/package.json
- standalone/standalone/test/fixtures/module-with-empty-default-config/foo.ts
- standalone/standalone/test/fixtures/module-with-empty-default-config/module.dev.yml
- standalone/standalone/test/fixtures/module-with-empty-default-config/package.json
- standalone/standalone/test/fixtures/multi-callback-instance-module/logger/DynamicLogger.ts
- standalone/standalone/test/index.test.ts
> fix: config for env is not merged when default config is empty

- core/aop-decorator/src/decorator/Pointcut.ts
使用 AOP Pointcut 时 adviceParams 参数类型是 any，体验不好，尝试加上了类型。
修改后可能会导致部分用户代码出现类型报错。
When using AOP Pointcut, the adviceParams parameter is any. The experience is not good, so I tried adding it.
Modification may cause type errors to occur in some user codes.
> chore: add type for adviceParams

- core/aop-runtime/src/AspectExecutor.ts
- core/aop-runtime/test/fixtures/modules/hello_succeed/Hello.ts
> fix: 修复aop丢失原引用，导致修改ctx的逻辑失效的问题

- README.md
- core/dynamic-inject-runtime/src/EggObjectFactory.ts
- core/dynamic-inject-runtime/test/fixtures/modules/dynamic-inject-module/HelloService.ts
- core/dynamic-inject-runtime/test/index.test.ts
- core/dynamic-inject/src/EggObjectFactory.ts
- core/dynamic-inject/src/QualifierImplUtil.ts
新增 `eggObjectFactory.getEggObjects` 接口，用于获取抽象类对应的所有实现。
> feat: add getEggObjects API to fetch all instances

- core/aop-runtime/src/PointCutGraphHook.ts
- core/core-decorator/src/util/QualifierUtil.ts
- core/dynamic-inject-runtime/src/EggObjectFactoryPrototype.ts
- core/metadata/src/impl/EggPrototypeBuilder.ts
- core/metadata/src/model/ProtoDescriptorHelper.ts
- core/metadata/src/model/graph/GlobalGraph.ts
- core/runtime/src/impl/EggObjectUtil.ts
- plugin/dal/lib/TransactionalAOP.ts
- plugin/tegg/lib/EggCompatibleProtoImpl.ts
- plugin/tegg/test/ConstructorModuleConfig.test.ts
- plugin/tegg/test/fixtures/apps/constructor-module-config/modules/module-with-config/foo.ts
> fix: fix merge qualifier
