core/lifecycle/src/IdenticalObject.ts
core/lifecycle/test/IdenticalObject.test.ts
plugin/orm/lib/LeoricRegister.ts

fix: fix objId bug

---

core/tegg/helper.ts
core/tegg/package.json
core/tegg/test/helper.test.ts

module-test-utils 是内部模块，不应该写进依赖

fix: remove module-test-utils

---

core/controller-decorator/src/impl/http/HTTPControllerMethodMetaBuilder.ts
core/controller-decorator/test/fixtures/HTTPFooController.ts
core/controller-decorator/test/http/HTTPMeta.test.ts
plugin/controller/test/fixtures/apps/controller-app/app/controller/ParamController.ts
plugin/controller/test/http/params.test.ts
plugin/controller/test/lib/EggControllerLoader.test.ts

fix: fix params in controller path

---

plugin/controller/lib/impl/http/HTTPMethodRegister.ts
plugin/controller/test/http/edgecase.test.ts

FIXES:
- https://github.com/eggjs/tegg/issues/15

fix: case sensitive same as egg router

---

plugin/eventbus/package.json

closes https://github.com/eggjs/tegg/issues/23

🐛 FIX: Add types property on eventbus

---

core/common-util/src/ModuleConfig.ts
core/common-util/test/ModuleConfig.test.ts

some typescript types are depended from test/fixtures/modules 
test shoule not be ignored

fix: should not ignore test files

---

core/tegg/package.json

fix: invalid value of main

---

core/loader/src/LoaderFactory.ts
plugin/controller/app.ts
plugin/controller/lib/ControllerLoadUnitHandler.ts
plugin/controller/lib/EggControllerLoader.ts
plugin/controller/lib/errors.ts
plugin/controller/lib/impl/http/HTTPMethodRegister.ts
plugin/controller/package.json
plugin/controller/test/lib/EggControllerLoader.test.ts
plugin/controller/test/lib/HTTPMethodRegister.test.ts
plugin/controller/typings/index.d.ts
plugin/tegg/app/extend/application.ts
plugin/tegg/typings/index.d.ts

refactor: add more exports

---

core/aop-decorator/src/AspectMetaBuilder.ts
core/aop-decorator/test/AspectMetaBuilder.test.ts
core/aop-decorator/test/fixtures/PointcutExample.ts

fix: aop meta builder should not access getter

---

core/aop-runtime/package.json
core/aop-runtime/src/LoadUnitAopHook.ts
core/aop-runtime/test/aop-runtime.test.ts
core/aop-runtime/test/fixtures/modules/should_throw/Hello.ts
core/aop-runtime/test/fixtures/modules/should_throw/package.json

fix: should throw with no aop proto

---

.eslintignore
.gitignore
benchmark/http/app/controller/FooTeggController.ts
benchmark/http/app/controller/template/egg_controller_1.js
benchmark/http/app/router.js
benchmark/http/config/config.default.js
benchmark/http/config/plugin.js
benchmark/http/package.json
benchmark/http/tsconfig.json
core/runtime/src/model/AbstractEggContext.ts
plugin/controller/app.ts
plugin/controller/lib/EggControllerHook.ts
plugin/tegg/app.ts
plugin/tegg/lib/AppLoadUnitInstance.ts
plugin/tegg/lib/EggContextCompatibleHook.ts

feat: skip compatible object when egg context init

---

core/core-decorator/src/decorator/Inject.ts
core/core-decorator/src/util/MetadataUtil.ts
core/core-decorator/src/util/PrototypeUtil.ts
core/core-decorator/test/decorators.test.ts
core/core-decorator/test/fixtures/decators/CacheService.ts
core/core-decorator/test/fixtures/decators/OtherService.ts
core/core-decorator/test/fixtures/decators/QualifierCacheService.ts
core/metadata/test/fixtures/modules/extends-module/Base.ts
core/runtime/test/fixtures/modules/extends-module/Base.ts
tsconfig.json

优化 Inject 逻辑，让 Inject 更简单易用，可以直接 Inject name ，也支持通过 design:type 来获取 protoClass
```typescript
@ContextProto()
export class TestService {
sayHi() {
console.info('hi');
}
}
@ContextProto()
export class TestService2 {
sayHi() {
console.info('hi');
}
}
@ContextProto()
export default class CacheService {
static fileName = __filename;
@Inject({
name: 'fooCache',
})
cache: ICache;
@Inject('testService')
testService: TestService;
@Inject()
otherService: TestService2;
}
```

feat: allow inject proto and name

---

core/orm-decorator/package.json
plugin/orm/package.json
plugin/orm/test/fixtures/apps/orm-app/modules/orm-module/model/Pkg.ts

deps: upgrade leoric to 2.x

---

.github/workflows/nodejs.yml

ci: add node 16/18 ci

---

core/controller-decorator/src/decorator/Middleware.ts
core/controller-decorator/test/Middleware.test.ts
core/controller-decorator/test/fixtures/MiddlewareController.ts
plugin/controller/README.md

feat: add middlewares decorator

---

core/eventbus-runtime/src/SingletonEventBus.ts
core/eventbus-runtime/test/EventBus.test.ts
core/eventbus-runtime/test/fixtures/modules/event/MultiEvent.ts

fix: eventbus runtime should wait all handlers done

---

core/aop-runtime/src/AspectExecutor.ts
core/eventbus-runtime/src/EventHandlerFactory.ts
package.json

fix: fix events type from any to keyof Events

---

.github/workflows/nodejs.yml
package.json

chore: use npm workspace

---

plugin/schedule/package.json

fix: fix miss agent file

---

core/common-util/src/ModuleConfig.ts

fix: none exist node_modules path

---

core/common-util/src/ModuleConfig.ts

fix: skip file not exits

---

standalone/standalone/src/Runner.ts
standalone/standalone/src/StandaloneContext.ts
standalone/standalone/test/fixtures/simple/foo.ts
standalone/standalone/test/index.test.ts

feat: standalone support context

---

core/aop-runtime/src/AspectExecutor.ts
core/aop-runtime/test/aop-runtime.test.ts

fix: fix mock prototype in aop not work

---

plugin/controller/package.json
plugin/orm/package.json
plugin/tegg/package.json

deps: fix sdk-base

---

core/controller-decorator/src/decorator/http/Host.ts
core/controller-decorator/src/impl/http/HTTPControllerMetaBuilder.ts
core/controller-decorator/src/impl/http/HTTPControllerMethodMetaBuilder.ts
core/controller-decorator/src/model/HTTPControllerMeta.ts
core/controller-decorator/src/model/HTTPMethodMeta.ts
core/controller-decorator/src/model/types.ts
core/controller-decorator/src/util/ControllerInfoUtil.ts
core/controller-decorator/src/util/MethodInfoUtil.ts
core/controller-decorator/test/Acl.test.ts
core/controller-decorator/test/http/Host.test.ts
plugin/controller/lib/impl/http/HTTPMethodRegister.ts
plugin/controller/test/fixtures/apps/host-controller-app/app/controller/AppController2.ts
plugin/controller/test/fixtures/apps/host-controller-app/app/controller/MultiHostController.ts
plugin/controller/test/fixtures/apps/host-controller-app/app/controller/MultiMethodHostController.ts
plugin/controller/test/http/host.test.ts

controller-decorator
Make the `@Host` decorator supports multiple host
@Host(string) => @Host(string | string[])

feat: multi host decorator

---

plugin/controller/package.json

@eggjs/tegg-controller-plugin
it's required by plugin/controller/lib/EggControllerLoader.ts

fix: add 'globby' as dependencies

---

core/runtime/src/impl/ContextObjectGraph.ts
core/runtime/test/EggObject.test.ts
core/runtime/test/fixtures/modules/inject-context-to-singleton/object.ts

fix: fix nest inject ctx obj to singleton obj

---

plugin/controller/package.json
plugin/eventbus/package.json
plugin/orm/package.json
plugin/tegg/package.json
plugin/tegg/typings/index.d.ts

chore: upgrade egg-tracer to v2

---

core/aop-decorator/package.json
core/aop-runtime/package.json
core/background-task/package.json
core/common-util/package.json
core/controller-decorator/package.json
core/core-decorator/package.json
core/dynamic-inject-runtime/package.json
core/dynamic-inject/package.json
core/eventbus-decorator/package.json
core/eventbus-runtime/package.json
core/lifecycle/package.json
core/loader/package.json
core/metadata/package.json
core/orm-decorator/package.json
core/runtime/package.json
core/schedule-decorator/package.json
core/standalone-decorator/package.json
core/tegg/package.json
core/test-util/package.json
package.json
plugin/aop/package.json
plugin/common/package.json
plugin/config/package.json
plugin/controller/package.json
plugin/eventbus/package.json
plugin/orm/package.json
plugin/schedule/package.json
plugin/tegg/package.json
standalone/standalone/package.json

test: move devDependencies to workspaces

---

core/lifecycle/src/LifycycleUtil.ts
core/metadata/src/factory/LoadUnitFactory.ts
core/runtime/src/factory/EggObjectFactory.ts
core/runtime/src/factory/LoadUnitInstanceFactory.ts
core/runtime/src/impl/ModuleLoadUnitInstance.ts
core/runtime/src/model/AbstractEggContext.ts
plugin/controller/lib/ControllerLoadUnitInstance.ts
plugin/tegg/lib/AppLoadUnitInstance.ts
plugin/tegg/test/BackgroundTask.test.ts

fix: release obj from LifecycleUtil after obj destroy

---

plugin/controller/lib/impl/http/HTTPControllerRegister.ts
plugin/controller/lib/impl/http/HTTPMethodRegister.ts
plugin/controller/package.json

* 修复 plugin/controller CI 报错
* 更新 type 定义，统一使用 egg 提供的 Router 类型
* 不再使用 router.url 字段

fix: router type

---

plugin/tegg/app.ts
plugin/tegg/typings/index.d.ts

feat: add app.eggContextHandler

---

plugin/tegg/lib/ctx_lifecycle_middleware.ts
plugin/tegg/test/app/extend/context.test.ts

fix: beginModuleScope should be reentrant

---

plugin/tegg/app.ts
plugin/tegg/lib/EggContextCompatibleHook.ts
plugin/tegg/test/app/extend/context.test.ts

fix: wait egg background task done before destroy tegg ctx

---

plugin/tegg/app.ts

fix: should not notify backgroundTaskHelper if teggContext not exists

---

plugin/tegg/app.ts
plugin/tegg/lib/Utils.ts
plugin/tegg/lib/run_in_background.ts
plugin/tegg/test/app/extend/context.test.ts

feat: append call stack for runInBackground

---

README.md
core/core-decorator/index.ts
core/core-decorator/src/decorator/EggQualifier.ts
core/core-decorator/src/enum/EggType.ts
core/eventbus-runtime/src/SingletonEventBus.ts
plugin/eventbus/lib/EventbusLoadUnitHook.ts
plugin/tegg/app.ts
plugin/tegg/lib/EggAppLoader.ts
plugin/tegg/lib/EggCompatibleObject.ts
plugin/tegg/lib/EggCompatibleProtoImpl.ts
plugin/tegg/lib/EggContextCompatibleHook.ts
plugin/tegg/lib/EggQualifierProtoHook.ts
plugin/tegg/test/EggCompatible.test.ts
plugin/tegg/test/fixtures/apps/background-app/app/extend/context.ts
plugin/tegg/test/fixtures/apps/background-app/modules/multi-module-background/BackgroundService.ts
plugin/tegg/test/fixtures/apps/egg-app/app/extend/application.ts
plugin/tegg/test/fixtures/apps/egg-app/app/extend/context.ts
plugin/tegg/test/fixtures/apps/egg-app/modules/multi-module-service/EggTypeService.ts
plugin/tegg/test/fixtures/apps/egg-app/modules/multi-module-service/SingletonFooService.ts

feat: use SingletonProto for egg ctx object

---

.github/workflows/nodejs.yml
core/loader/package.json
core/loader/src/LoaderFactory.ts
core/loader/src/impl/ModuleLoader.ts

fix: loader should not deps metadata

---

core/eventbus-decorator/src/EventBus.ts
core/eventbus-runtime/src/SingletonEventBus.ts
plugin/eventbus/lib/EggContextEventBus.ts
plugin/eventbus/test/eventbus.test.ts

fix: eventbus cork should support reentry

---

plugin/tegg/lib/CompatibleUtil.ts
plugin/tegg/lib/EggAppLoader.ts
plugin/tegg/lib/EggQualifierProtoHook.ts

fix: not create ctx logger proto

---

plugin/tegg/app.ts
plugin/tegg/lib/ModuleHandler.ts

fix: egg qualifier should register after all file loaded

---

README.md
core/background-task/src/BackgroundTaskHelper.ts
plugin/tegg/test/BackgroundTask.test.ts
plugin/tegg/test/fixtures/apps/background-app/config/config.default.js
plugin/tegg/test/fixtures/apps/background-app/modules/multi-module-background/BackgroundService.ts

feat: add backgroundTask.timeout config

---

plugin/tegg/lib/EggQualifierProtoHook.ts

fix: get app/ctx properties when load unit beforeCreate

---

plugin/tegg/lib/EggCompatibleObject.ts
plugin/tegg/test/EggCompatible.test.ts

fix: should not cache ctx object

---

plugin/controller/README.md

docs: Update next param ts def

---

plugin/eventbus/package.json

fix: don't check eventbus plugin name

---

core/aop-decorator/index.ts
core/aop-decorator/src/decorator/Advice.ts
core/aop-decorator/src/decorator/Crosscut.ts
core/aop-decorator/src/decorator/Pointcut.ts
core/aop-decorator/src/model/Aspect.ts
core/aop-decorator/test/AspectMetaBuilder.test.ts
core/aop-decorator/test/fixtures/InheritExample.ts
core/aop-runtime/src/AspectExecutor.ts
core/aop-runtime/test/aop-runtime.test.ts
core/aop-runtime/test/fixtures/modules/hello_succeed/Hello.ts
plugin/aop/README.md

aop decorator 中增加 adviceParams 用于 IAdvice 执行时获取 decorator 上下文

feat: aop 支持 decorator 入参

---

standalone/standalone/index.ts
standalone/standalone/src/Runner.ts
standalone/standalone/test/fixtures/custom-context/foo.ts
standalone/standalone/test/fixtures/custom-context/package.json
standalone/standalone/test/index.test.ts

feat: standalone Runner run support ctx

---

core/common-util/src/ModuleConfig.ts

Closes:
- https://github.com/eggjs/tegg/issues/121

fix: use posix join for package path

---

core/tegg/package.json
core/tegg/transaction.ts

feat: export transaction decorator from tegg

---

plugin/tegg/package.json

chore: typo fix directory on package.json

---

standalone/standalone/index.ts

fix: export StandaloneInnerObject

---

plugin/eventbus/test/eventbus.test.ts
plugin/tegg/app/extend/application.unittest.ts
plugin/tegg/test/app/extend/application.unittest.test.ts

fix: after call mockModuleContext, hasMockModuleContext should be true

---

standalone/standalone/README.md
standalone/standalone/src/ConfigSource.ts
standalone/standalone/src/ConfigSourceLoadUnitHook.ts
standalone/standalone/src/ModuleConfig.ts
standalone/standalone/src/ModuleConfigs.ts
standalone/standalone/src/Runner.ts
standalone/standalone/src/StandaloneLoadUnit.ts
standalone/standalone/test/fixtures/module-with-config/foo.ts
standalone/standalone/test/fixtures/module-with-config/module.yml
standalone/standalone/test/fixtures/module-with-config/package.json
standalone/standalone/test/fixtures/multi-modules/bar/module.yml
standalone/standalone/test/fixtures/multi-modules/bar/package.json
standalone/standalone/test/fixtures/multi-modules/foo/foo.ts
standalone/standalone/test/fixtures/multi-modules/foo/module.yml
standalone/standalone/test/fixtures/multi-modules/foo/package.json
standalone/standalone/test/index.test.ts

feat: impl ModuleConfigs for standalone

---

plugin/aop/package.json

fix: fix aop plugin files

---

plugin/tegg/app.ts

feat: add LoadUnitMultiInstanceProtoHook for tegg plugin

---

plugin/orm/lib/LeoricRegister.ts
plugin/orm/package.json
standalone/standalone/src/Runner.ts

fix: fix standalone import ConfigSource

---

core/runtime/src/factory/EggContainerFactory.ts
core/runtime/test/LoadUnitInstance.test.ts
plugin/tegg/app/extend/application.ts

MultiInstanceProto also has proto.

fix: verify isEggMultiInstancePrototype before proto exists

---

core/controller-decorator/src/model/types.ts

feat: Add ControllerType = SCHEDULE

---

README.md
core/runtime/src/factory/EggContainerFactory.ts
core/runtime/test/EggObject.test.ts
plugin/tegg/app/extend/application.ts
plugin/tegg/app/extend/context.ts
plugin/tegg/test/app/extend/context.test.ts
plugin/tegg/typings/index.d.ts

feat: impl getObjectFromName

---

plugin/tegg/test/ModuleConfig.test.ts

ref: https://github.com/eggjs/tegg/pull/169#pullrequestreview-1773699829

test(plugin/tegg): delete mock module config line code

---

plugin/tegg/app.ts
plugin/tegg/test/close.test.ts

fix: clear all hooks after app close

---

.gitignore
plugin/config/lib/ModuleScanner.ts
plugin/config/test/DuplicateOptionalModule.test.ts
plugin/config/test/fixtures/apps/duplicate-optional-module/config/config.default.js
plugin/config/test/fixtures/apps/duplicate-optional-module/config/plugin.js
plugin/config/test/fixtures/apps/duplicate-optional-module/node_modules/foo/package.json
plugin/config/test/fixtures/apps/duplicate-optional-module/node_modules/unused/Unused.js
plugin/config/test/fixtures/apps/duplicate-optional-module/node_modules/unused/package.json
plugin/config/test/fixtures/apps/duplicate-optional-module/node_modules/used/Used.js
plugin/config/test/fixtures/apps/duplicate-optional-module/node_modules/used/package.json
plugin/config/test/fixtures/apps/duplicate-optional-module/package.json

fix: ignore duplicated module

---

core/dal-runtime/package.json

fix: add dal templates

---

core/dal-runtime/package.json

fix: fix dal templates build

---

.github/workflows/nodejs.yml
plugin/controller/package.json
plugin/orm/lib/LeoricRegister.ts

fix: phantom dependency

---

README.md
core/core-decorator/src/util/QualifierUtil.ts
core/dynamic-inject/src/QualifierImplDecoratorUtil.ts
core/dynamic-inject/src/QualifierImplUtil.ts
core/types/dynamic-inject.ts
plugin/tegg/lib/AppLoadUnit.ts

[pick]fix: add qualifier check

---

README.md
core/core-decorator/src/util/QualifierUtil.ts
core/dynamic-inject/src/QualifierImplDecoratorUtil.ts
core/dynamic-inject/src/QualifierImplUtil.ts
core/types/dynamic-inject.ts
plugin/tegg/lib/AppLoadUnit.ts

Revert "[pick]fix: add qualifier check"

---

.github/workflows/ci.yml
core/aop-decorator/test/AspectMetaBuilder.test.ts
core/aop-decorator/test/fixtures/PointcutExample.ts
core/controller-decorator/test/decorators.test.ts
core/controller-decorator/test/fixtures/HTTPFooController.ts
core/core-decorator/test/decorators.test.ts
core/core-decorator/test/fixtures/decators/CacheService.ts
core/dal-runtime/test/DAO.test.ts
core/dal-runtime/test/DataSource.test.ts
core/loader/src/LoaderUtil.ts
package.json
plugin/schedule/package.json
plugin/tegg/test/app/extend/context.test.ts
standalone/standalone/package.json
standalone/standalone/test/index.test.ts
standalone/standalone/tsconfig.build.json
standalone/standalone/tsconfig.json
vitest.config.ts

help by gpt https://chatgpt.com/share/68e356b6-d2dc-8010-a566-28f11a9a6dee

test: ci on Node.js 20 and Windows
